{"name": "Проверка ошибки создания юзера: повторное создание существующего юзера", "status": "passed", "start": 1701370918584, "stop": 1701370918772, "uuid": "019f9e90-95ec-4c73-a4a5-6a1f07e83636", "historyId": "261d3a732b6c1a88954212563e36c67b", "testCaseId": "261d3a732b6c1a88954212563e36c67b", "fullName": "tests.test_user_register.TestUserRegistration#test_register_duplicate_user_failed_registration", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_register"}, {"name": "subSuite", "value": "TestUserRegistration"}, {"name": "host", "value": "WKS-084"}, {"name": "thread", "value": "5364-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_register"}]}